export default {     
    majors: [
    { name: "Accounting", value: "Accounting" },
    { name: "Aerospace Engineering", value: "Aerospace Engineering" },
    { name: "Anthropology", value: "Anthropology" },
    { name: "Architecture", value: "Architecture" },
    { name: "Art History", value: "Art History" },
    { name: "Biochemistry", value: "Biochemistry" },
    { name: "Biology", value: "Biology" },
    { name: "Biomedical Engineering", value: "Biomedical Engineering" },
    { name: "Business Administration", value: "Business Administration" },
    { name: "Chemical Engineering", value: "Chemical Engineering" },
    { name: "Chemistry", value: "Chemistry" },
    { name: "Civil Engineering", value: "Civil Engineering" },
    { name: "Communications", value: "Communications" },
    { name: "Computer Engineering", value: "Computer Engineering" },
    { name: "Computer Science", value: "Computer Science" },
    { name: "Criminal Justice", value: "Criminal Justice" },
    { name: "Economics", value: "Economics" },
    { name: "Education", value: "Education" },
    { name: "Electrical Engineering", value: "Electrical Engineering" },
    { name: "English", value: "English" },
    { name: "Environmental Science", value: "Environmental Science" },
    { name: "Finance", value: "Finance" },
    { name: "Fine Arts", value: "Fine Arts" },
    { name: "Geography", value: "Geography" },
    { name: "Geology", value: "Geology" },
    { name: "History", value: "History" },
    { name: "Industrial Engineering", value: "Industrial Engineering" },
    { name: "Information Technology", value: "Information Technology" },
    { name: "International Relations", value: "International Relations" },
    { name: "Journalism", value: "Journalism" },
    { name: "Law", value: "Law" },
    { name: "Management", value: "Management" },
    { name: "Marketing", value: "Marketing" },
    { name: "Mathematics", value: "Mathematics" },
    { name: "Mechanical Engineering", value: "Mechanical Engineering" },
    { name: "Medicine", value: "Medicine" },
    { name: "Microbiology", value: "Microbiology" },
    { name: "Music", value: "Music" },
    { name: "Nursing", value: "Nursing" },
    { name: "Philosophy", value: "Philosophy" },
    { name: "Physics", value: "Physics" },
    { name: "Political Science", value: "Political Science" },
    { name: "Psychology", value: "Psychology" },
    { name: "Public Health", value: "Public Health" },
    { name: "Sociology", value: "Sociology" },
    { name: "Software Engineering", value: "Software Engineering" },
    { name: "Statistics", value: "Statistics" },
    { name: "Theater", value: "Theater" }
]}
