name: AWS DEPLOY TO STAGING

#turn off deploy to AWS
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    #For google auth

    steps:
      - uses: actions/checkout@v3

        with:
          ref: main
      - uses: actions/setup-node@v4

        with:
          node-version: 20.11.0

      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
